services:
  app:
    build:
      target: builder
    container_name: backend-app-dev
    restart: "no"
    volumes:
      - ./:/app
      - go-modules:/go/pkg/mod
    command: ["go", "run", "github.com/air-verse/air@latest", "-c", ".air.toml"]
    environment:
      - ENVIRONMENT=development

  postgres:
    volumes:
      - ./.docker-local/postgres:/var/lib/postgresql

  redis:
    volumes:
      - ./.docker-local/redis:/data

volumes:
  go-modules:
