# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    App\Tests\Double\FakeScheduleValidationClient:
        public: true

    App\Service\ScheduleValidation\ScheduleValidationClientInterface:
        alias: App\Tests\Double\FakeScheduleValidationClient
