<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511101829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE academic_years (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE action_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, admin_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B2C5F685642B8210 ON action_log (admin_id)');
        $this->addSql('CREATE TABLE admins (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2E0150FE7927C74 ON admins (email)');
        $this->addSql('CREATE TABLE exam_groups (exam_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (exam_id, group_id))');
        $this->addSql('CREATE INDEX IDX_3B5E6FFA578D5E91 ON exam_groups (exam_id)');
        $this->addSql('CREATE INDEX IDX_3B5E6FFAFE54D947 ON exam_groups (group_id)');
        $this->addSql('CREATE TABLE exams (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exam_date DATE NOT NULL, starts_at TIME(0) WITHOUT TIME ZONE NOT NULL, semester_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, room_id BIGINT NOT NULL, created_by BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_693113284A798B6F ON exams (semester_id)');
        $this->addSql('CREATE INDEX IDX_6931132823EDC87 ON exams (subject_id)');
        $this->addSql('CREATE INDEX IDX_6931132841807E1D ON exams (teacher_id)');
        $this->addSql('CREATE INDEX IDX_6931132854177093 ON exams (room_id)');
        $this->addSql('CREATE INDEX IDX_69311328DE12AB56 ON exams (created_by)');
        $this->addSql('CREATE TABLE groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, speciality VARCHAR(255) NOT NULL, course INT NOT NULL, student_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lesson_groups (lesson_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (lesson_id, group_id))');
        $this->addSql('CREATE INDEX IDX_83FBC927CDF80196 ON lesson_groups (lesson_id)');
        $this->addSql('CREATE INDEX IDX_83FBC927FE54D947 ON lesson_groups (group_id)');
        $this->addSql('CREATE TABLE lessons (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_date DATE NOT NULL, lesson_type SMALLINT NOT NULL, is_cancelled BOOLEAN NOT NULL, is_override BOOLEAN NOT NULL, schedule_entry_id BIGINT DEFAULT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, room_id BIGINT NOT NULL, time_slot_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F4218D96DDA074 ON lessons (schedule_entry_id)');
        $this->addSql('CREATE INDEX IDX_3F4218D923EDC87 ON lessons (subject_id)');
        $this->addSql('CREATE INDEX IDX_3F4218D941807E1D ON lessons (teacher_id)');
        $this->addSql('CREATE INDEX IDX_3F4218D954177093 ON lessons (room_id)');
        $this->addSql('CREATE INDEX IDX_3F4218D9D62B0FA ON lessons (time_slot_id)');
        $this->addSql('CREATE TABLE rooms (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE schedule_entries (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_type SMALLINT NOT NULL, day_of_week SMALLINT NOT NULL, week_parity SMALLINT NOT NULL, schedule_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, room_id BIGINT NOT NULL, time_slot_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0929F74A40BC2D5 ON schedule_entries (schedule_id)');
        $this->addSql('CREATE INDEX IDX_A0929F7423EDC87 ON schedule_entries (subject_id)');
        $this->addSql('CREATE INDEX IDX_A0929F7441807E1D ON schedule_entries (teacher_id)');
        $this->addSql('CREATE INDEX IDX_A0929F7454177093 ON schedule_entries (room_id)');
        $this->addSql('CREATE INDEX IDX_A0929F74D62B0FA ON schedule_entries (time_slot_id)');
        $this->addSql('CREATE TABLE schedule_entry_groups (schedule_entry_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (schedule_entry_id, group_id))');
        $this->addSql('CREATE INDEX IDX_C372BC1C6DDA074 ON schedule_entry_groups (schedule_entry_id)');
        $this->addSql('CREATE INDEX IDX_C372BC1CFE54D947 ON schedule_entry_groups (group_id)');
        $this->addSql('CREATE TABLE schedule_entry_teaching_loads (schedule_entry_id BIGINT NOT NULL, teaching_load_id BIGINT NOT NULL, PRIMARY KEY (schedule_entry_id, teaching_load_id))');
        $this->addSql('CREATE INDEX IDX_F859A5A36DDA074 ON schedule_entry_teaching_loads (schedule_entry_id)');
        $this->addSql('CREATE INDEX IDX_F859A5A376F1A576 ON schedule_entry_teaching_loads (teaching_load_id)');
        $this->addSql('CREATE TABLE schedules (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, valid_from DATE NOT NULL, valid_to DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, semester_id BIGINT NOT NULL, created_by BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_313BDC8E4A798B6F ON schedules (semester_id)');
        $this->addSql('CREATE INDEX IDX_313BDC8EDE12AB56 ON schedules (created_by)');
        $this->addSql('CREATE TABLE semesters (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, first_week_parity SMALLINT NOT NULL, academic_year_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5426940C54F3401 ON semesters (academic_year_id)');
        $this->addSql('CREATE TABLE subjects (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE teacher_subjects (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, teacher_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA332A9C41807E1D ON teacher_subjects (teacher_id)');
        $this->addSql('CREATE INDEX IDX_AA332A9C23EDC87 ON teacher_subjects (subject_id)');
        $this->addSql('CREATE TABLE teacher_unavailability (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week SMALLINT NOT NULL, unavailable_from TIME(0) WITHOUT TIME ZONE NOT NULL, unavailable_to TIME(0) WITHOUT TIME ZONE NOT NULL, teacher_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58A0E27A41807E1D ON teacher_unavailability (teacher_id)');
        $this->addSql('CREATE TABLE teachers (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, department VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE teaching_loads (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_type SMALLINT NOT NULL, required_lesson_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, semester_id BIGINT NOT NULL, group_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B132A71A4A798B6F ON teaching_loads (semester_id)');
        $this->addSql('CREATE INDEX IDX_B132A71AFE54D947 ON teaching_loads (group_id)');
        $this->addSql('CREATE INDEX IDX_B132A71A23EDC87 ON teaching_loads (subject_id)');
        $this->addSql('CREATE INDEX IDX_B132A71A41807E1D ON teaching_loads (teacher_id)');
        $this->addSql('CREATE TABLE telegram_subscriptions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telegram_chat_id BIGINT NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE time_slots (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, starts_at TIME(0) WITHOUT TIME ZONE NOT NULL, ends_at TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE action_log ADD CONSTRAINT FK_B2C5F685642B8210 FOREIGN KEY (admin_id) REFERENCES admins (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_groups ADD CONSTRAINT FK_3B5E6FFA578D5E91 FOREIGN KEY (exam_id) REFERENCES exams (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_groups ADD CONSTRAINT FK_3B5E6FFAFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_693113284A798B6F FOREIGN KEY (semester_id) REFERENCES semesters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132823EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132841807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132854177093 FOREIGN KEY (room_id) REFERENCES rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_69311328DE12AB56 FOREIGN KEY (created_by) REFERENCES admins (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_groups ADD CONSTRAINT FK_83FBC927CDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_groups ADD CONSTRAINT FK_83FBC927FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D96DDA074 FOREIGN KEY (schedule_entry_id) REFERENCES schedule_entries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D923EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D941807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D954177093 FOREIGN KEY (room_id) REFERENCES rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D9D62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slots (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entries ADD CONSTRAINT FK_A0929F74A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entries ADD CONSTRAINT FK_A0929F7423EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entries ADD CONSTRAINT FK_A0929F7441807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entries ADD CONSTRAINT FK_A0929F7454177093 FOREIGN KEY (room_id) REFERENCES rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entries ADD CONSTRAINT FK_A0929F74D62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slots (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entry_groups ADD CONSTRAINT FK_C372BC1C6DDA074 FOREIGN KEY (schedule_entry_id) REFERENCES schedule_entries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entry_groups ADD CONSTRAINT FK_C372BC1CFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entry_teaching_loads ADD CONSTRAINT FK_F859A5A36DDA074 FOREIGN KEY (schedule_entry_id) REFERENCES schedule_entries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule_entry_teaching_loads ADD CONSTRAINT FK_F859A5A376F1A576 FOREIGN KEY (teaching_load_id) REFERENCES teaching_loads (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8E4A798B6F FOREIGN KEY (semester_id) REFERENCES semesters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8EDE12AB56 FOREIGN KEY (created_by) REFERENCES admins (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE semesters ADD CONSTRAINT FK_C5426940C54F3401 FOREIGN KEY (academic_year_id) REFERENCES academic_years (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_subjects ADD CONSTRAINT FK_AA332A9C41807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_subjects ADD CONSTRAINT FK_AA332A9C23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_unavailability ADD CONSTRAINT FK_58A0E27A41807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teaching_loads ADD CONSTRAINT FK_B132A71A4A798B6F FOREIGN KEY (semester_id) REFERENCES semesters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teaching_loads ADD CONSTRAINT FK_B132A71AFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teaching_loads ADD CONSTRAINT FK_B132A71A23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teaching_loads ADD CONSTRAINT FK_B132A71A41807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action_log DROP CONSTRAINT FK_B2C5F685642B8210');
        $this->addSql('ALTER TABLE exam_groups DROP CONSTRAINT FK_3B5E6FFA578D5E91');
        $this->addSql('ALTER TABLE exam_groups DROP CONSTRAINT FK_3B5E6FFAFE54D947');
        $this->addSql('ALTER TABLE exams DROP CONSTRAINT FK_693113284A798B6F');
        $this->addSql('ALTER TABLE exams DROP CONSTRAINT FK_6931132823EDC87');
        $this->addSql('ALTER TABLE exams DROP CONSTRAINT FK_6931132841807E1D');
        $this->addSql('ALTER TABLE exams DROP CONSTRAINT FK_6931132854177093');
        $this->addSql('ALTER TABLE exams DROP CONSTRAINT FK_69311328DE12AB56');
        $this->addSql('ALTER TABLE lesson_groups DROP CONSTRAINT FK_83FBC927CDF80196');
        $this->addSql('ALTER TABLE lesson_groups DROP CONSTRAINT FK_83FBC927FE54D947');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D96DDA074');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D923EDC87');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D941807E1D');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D954177093');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D9D62B0FA');
        $this->addSql('ALTER TABLE schedule_entries DROP CONSTRAINT FK_A0929F74A40BC2D5');
        $this->addSql('ALTER TABLE schedule_entries DROP CONSTRAINT FK_A0929F7423EDC87');
        $this->addSql('ALTER TABLE schedule_entries DROP CONSTRAINT FK_A0929F7441807E1D');
        $this->addSql('ALTER TABLE schedule_entries DROP CONSTRAINT FK_A0929F7454177093');
        $this->addSql('ALTER TABLE schedule_entries DROP CONSTRAINT FK_A0929F74D62B0FA');
        $this->addSql('ALTER TABLE schedule_entry_groups DROP CONSTRAINT FK_C372BC1C6DDA074');
        $this->addSql('ALTER TABLE schedule_entry_groups DROP CONSTRAINT FK_C372BC1CFE54D947');
        $this->addSql('ALTER TABLE schedule_entry_teaching_loads DROP CONSTRAINT FK_F859A5A36DDA074');
        $this->addSql('ALTER TABLE schedule_entry_teaching_loads DROP CONSTRAINT FK_F859A5A376F1A576');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8E4A798B6F');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8EDE12AB56');
        $this->addSql('ALTER TABLE semesters DROP CONSTRAINT FK_C5426940C54F3401');
        $this->addSql('ALTER TABLE teacher_subjects DROP CONSTRAINT FK_AA332A9C41807E1D');
        $this->addSql('ALTER TABLE teacher_subjects DROP CONSTRAINT FK_AA332A9C23EDC87');
        $this->addSql('ALTER TABLE teacher_unavailability DROP CONSTRAINT FK_58A0E27A41807E1D');
        $this->addSql('ALTER TABLE teaching_loads DROP CONSTRAINT FK_B132A71A4A798B6F');
        $this->addSql('ALTER TABLE teaching_loads DROP CONSTRAINT FK_B132A71AFE54D947');
        $this->addSql('ALTER TABLE teaching_loads DROP CONSTRAINT FK_B132A71A23EDC87');
        $this->addSql('ALTER TABLE teaching_loads DROP CONSTRAINT FK_B132A71A41807E1D');
        $this->addSql('DROP TABLE academic_years');
        $this->addSql('DROP TABLE action_log');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE exam_groups');
        $this->addSql('DROP TABLE exams');
        $this->addSql('DROP TABLE groups');
        $this->addSql('DROP TABLE lesson_groups');
        $this->addSql('DROP TABLE lessons');
        $this->addSql('DROP TABLE rooms');
        $this->addSql('DROP TABLE schedule_entries');
        $this->addSql('DROP TABLE schedule_entry_groups');
        $this->addSql('DROP TABLE schedule_entry_teaching_loads');
        $this->addSql('DROP TABLE schedules');
        $this->addSql('DROP TABLE semesters');
        $this->addSql('DROP TABLE subjects');
        $this->addSql('DROP TABLE teacher_subjects');
        $this->addSql('DROP TABLE teacher_unavailability');
        $this->addSql('DROP TABLE teachers');
        $this->addSql('DROP TABLE teaching_loads');
        $this->addSql('DROP TABLE telegram_subscriptions');
        $this->addSql('DROP TABLE time_slots');
    }
}
