<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260513143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace flat exams with exam schedules and exam schedule entries.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE exam_groups');
        $this->addSql('DROP TABLE exams');
        $this->addSql('CREATE TABLE exam_schedules (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, semester_id BIGINT NOT NULL, created_by BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D93A7A404A798B6F ON exam_schedules (semester_id)');
        $this->addSql('CREATE INDEX IDX_D93A7A40DE12AB56 ON exam_schedules (created_by)');
        $this->addSql('CREATE TABLE exam_schedule_entries (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, entry_date DATE NOT NULL, starts_at TIME(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exam_schedule_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, room_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6184B609FF31C2DE ON exam_schedule_entries (exam_schedule_id)');
        $this->addSql('CREATE INDEX IDX_6184B60923EDC87 ON exam_schedule_entries (subject_id)');
        $this->addSql('CREATE INDEX IDX_6184B60941807E1D ON exam_schedule_entries (teacher_id)');
        $this->addSql('CREATE INDEX IDX_6184B60954177093 ON exam_schedule_entries (room_id)');
        $this->addSql('CREATE TABLE exam_schedule_entry_groups (exam_schedule_entry_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (exam_schedule_entry_id, group_id))');
        $this->addSql('CREATE INDEX IDX_565D2A97FE54D947 ON exam_schedule_entry_groups (group_id)');
        $this->addSql('CREATE INDEX IDX_565D2A97EBF9929D ON exam_schedule_entry_groups (exam_schedule_entry_id)');
        $this->addSql('ALTER TABLE exam_schedules ADD CONSTRAINT FK_D93A7A404A798B6F FOREIGN KEY (semester_id) REFERENCES semesters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedules ADD CONSTRAINT FK_D93A7A40DE12AB56 FOREIGN KEY (created_by) REFERENCES admins (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entries ADD CONSTRAINT FK_6184B609FF31C2DE FOREIGN KEY (exam_schedule_id) REFERENCES exam_schedules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entries ADD CONSTRAINT FK_6184B60923EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entries ADD CONSTRAINT FK_6184B60941807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entries ADD CONSTRAINT FK_6184B60954177093 FOREIGN KEY (room_id) REFERENCES rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entry_groups ADD CONSTRAINT FK_565D2A97EBF9929D FOREIGN KEY (exam_schedule_entry_id) REFERENCES exam_schedule_entries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_schedule_entry_groups ADD CONSTRAINT FK_565D2A97FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE exam_schedule_entry_groups DROP CONSTRAINT FK_565D2A97EBF9929D');
        $this->addSql('ALTER TABLE exam_schedule_entry_groups DROP CONSTRAINT FK_565D2A97FE54D947');
        $this->addSql('ALTER TABLE exam_schedule_entries DROP CONSTRAINT FK_6184B609FF31C2DE');
        $this->addSql('ALTER TABLE exam_schedule_entries DROP CONSTRAINT FK_6184B60923EDC87');
        $this->addSql('ALTER TABLE exam_schedule_entries DROP CONSTRAINT FK_6184B60941807E1D');
        $this->addSql('ALTER TABLE exam_schedule_entries DROP CONSTRAINT FK_6184B60954177093');
        $this->addSql('ALTER TABLE exam_schedules DROP CONSTRAINT FK_D93A7A404A798B6F');
        $this->addSql('ALTER TABLE exam_schedules DROP CONSTRAINT FK_D93A7A40DE12AB56');
        $this->addSql('DROP TABLE exam_schedule_entry_groups');
        $this->addSql('DROP TABLE exam_schedule_entries');
        $this->addSql('DROP TABLE exam_schedules');
        $this->addSql('CREATE TABLE exams (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exam_date DATE NOT NULL, starts_at TIME(0) WITHOUT TIME ZONE NOT NULL, semester_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL, room_id BIGINT NOT NULL, created_by BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_693113284A798B6F ON exams (semester_id)');
        $this->addSql('CREATE INDEX IDX_6931132823EDC87 ON exams (subject_id)');
        $this->addSql('CREATE INDEX IDX_6931132841807E1D ON exams (teacher_id)');
        $this->addSql('CREATE INDEX IDX_6931132854177093 ON exams (room_id)');
        $this->addSql('CREATE INDEX IDX_69311328DE12AB56 ON exams (created_by)');
        $this->addSql('CREATE TABLE exam_groups (exam_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (exam_id, group_id))');
        $this->addSql('CREATE INDEX IDX_3B5E6FFA578D5E91 ON exam_groups (exam_id)');
        $this->addSql('CREATE INDEX IDX_3B5E6FFAFE54D947 ON exam_groups (group_id)');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_693113284A798B6F FOREIGN KEY (semester_id) REFERENCES semesters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132823EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132841807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_6931132854177093 FOREIGN KEY (room_id) REFERENCES rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exams ADD CONSTRAINT FK_69311328DE12AB56 FOREIGN KEY (created_by) REFERENCES admins (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_groups ADD CONSTRAINT FK_3B5E6FFA578D5E91 FOREIGN KEY (exam_id) REFERENCES exams (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_groups ADD CONSTRAINT FK_3B5E6FFAFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE');
    }
}
